name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.63
          - 1.85
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - if: ${{ matrix.rust == 'stable' }}
        run: cargo fmt -- --color=always --check
      - if: ${{ matrix.rust == '1.63' }}
        run: cargo build --features=rand_core_0_5,rand_core_0_6,rand_core_0_9
      - if: ${{ matrix.rust != '1.63' }}
        run: cargo build --all-features
